### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by nishant-shah-social** [coltdorsey/cypress-iap#30]
On windows, the execution of awk command is causing an issue.
This is what I get while executing on a windows machine :-
 Stderr:
[15:38:46][Step 3/4] awk: '/location/
[15:38:46][Step 3/4] awk: ^ invalid char ''' in expression

Looks like issue with single quotes not been recognized in windows cmd

Can we fix this? It would be super useful for us
Thanks in advance

**Comment by nishant-shah-social** [comment]
@coltdorsey I have a PR for windows support ready on my local..
If you can grant me required permission to contribute on this repo, I will raise the PR

**Comment by coltdorsey** [comment]
@nishant-shah-social Hey, thanks for your work. You should be able to fork this repo, push up your changes and make a pull request to this repository.

**Comment by coltdorsey** [comment]
@nishant-shah-social It looks like you are maintaining your own solution for windows. I'll go ahead and close this.
