### ISSUE TITLE
Plugin does not work anymore for me

### ISSUE THREAD

**Issue by nishant-shah-social** [coltdorsey/cypress-iap#31]
Hello,
This plugin was working fine until last week, but looks like its not working anymore and I am unable to perform IAP login with it in my cypress tests.
Looks like Google has dropped the logic of performing IAP login via the cookie :- GCP_IAAP_AUTH_TOKEN
Someone from google recently updated this blog :- https://cloud.google.com/blog/products/identity-security/getting-started-with-cloud-identity-aware-proxy and removed this cookie name as well.

@coltdorsey does it still work for you?
If not then are you planning to update this plugin to make it work again?

Thanks,
Nishant Shah

**Comment by coltdorsey** [comment]
@nishant-shah-social Unfortunately this is no longer working for me either. I'll be looking in to this issue now :)

**Comment by nishant-shah-social** [comment]
@coltdorsey I had already reached out to Google folks for this. It seems that they have stopped supporting the Cookie way of doing programmatic IAP.
There is only one option left for performing programmatic IAP and i.e. to add a header
`Authorize: Bearer <token>`
to each request going from your cypress tests
Some reference links:-
https://stackoverflow.com/questions/70762976/sporadic-redirects-by-iap-despite-valid-cookie-recent-development-started-on-f/70820466#70820466
https://cloud.google.com/blog/products/identity-security/getting-started-with-cloud-identity-aware-proxy

**Comment by coltdorsey** [comment]
@nishant-shah-social Thanks for the referenced links. A fix is in place which uses the [Proxy-Authorization](https://cloud.google.com/iap/docs/authentication-howto#authenticating_from_proxy-authorization_header). cypress-iap v2.0.0 was released 5 days ago. I forgot to let you know :)
